./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
./KVStoreGrader.sh >> log.file
